name: digital_signage
description: Digital Signage Enterprise App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  google_fonts: ^8.0.2
  file_picker: ^11.0.2
  minio: ^3.5.8
  video_player: ^2.10.1
  shared_preferences: ^2.5.5
  uuid: ^4.5.3
  path_provider: ^2.1.5
  http: ^1.6.0
  video_player_win: ^3.2.2
  window_manager: ^0.5.1
  qr_flutter: ^4.1.0
  video_thumbnail: ^0.5.3
  launch_at_startup: ^0.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Registering the new logo folder
  assets:
    - assets/images/kiosk.png

# Configuration to automatically generate the app icons
flutter_launcher_icons:
  image_path: "assets/images/kiosk.png"
  windows:
    generate: true
    image_path: "assets/images/kiosk.png"
  web:
    generate: true
    image_path: "assets/images/kiosk.png"