// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwwpSHRVO26JzXgxDiXARCqPCmwhq8KPw',
    appId: '1:926555713725:web:2d77fe0d5fa05d9a01c7d4',
    messagingSenderId: '926555713725',
    projectId: 'digital-signage-ae574',
    authDomain: 'digital-signage-ae574.firebaseapp.com',
    storageBucket: 'digital-signage-ae574.firebasestorage.app',
    measurementId: 'G-1GETVBTC74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgIwvzLI8KUsXS3KgYNxP4rLenLj6qGA',
    appId: '1:926555713725:android:e4fd0ed2db5f646801c7d4',
    messagingSenderId: '926555713725',
    projectId: 'digital-signage-ae574',
    storageBucket: 'digital-signage-ae574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSnjzrjOIIoLkaGyTG9Fe2c1ZOt0TjI78',
    appId: '1:926555713725:ios:26ab7211350df44901c7d4',
    messagingSenderId: '926555713725',
    projectId: 'digital-signage-ae574',
    storageBucket: 'digital-signage-ae574.firebasestorage.app',
    iosBundleId: 'com.example.digitalSignage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSnjzrjOIIoLkaGyTG9Fe2c1ZOt0TjI78',
    appId: '1:926555713725:ios:26ab7211350df44901c7d4',
    messagingSenderId: '926555713725',
    projectId: 'digital-signage-ae574',
    storageBucket: 'digital-signage-ae574.firebasestorage.app',
    iosBundleId: 'com.example.digitalSignage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwwpSHRVO26JzXgxDiXARCqPCmwhq8KPw',
    appId: '1:926555713725:web:0298c60801fd481501c7d4',
    messagingSenderId: '926555713725',
    projectId: 'digital-signage-ae574',
    authDomain: 'digital-signage-ae574.firebaseapp.com',
    storageBucket: 'digital-signage-ae574.firebasestorage.app',
    measurementId: 'G-7KBZCZ28QS',
  );

}